package xcvf.top.readercore.bean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import xcvf.top.readercore.bean.Green;
import xcvf.top.readercore.bean.TestDemo;

import xcvf.top.readercore.bean.GreenDao;
import xcvf.top.readercore.bean.TestDemoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig greenDaoConfig;
    private final DaoConfig testDemoDaoConfig;

    private final GreenDao greenDao;
    private final TestDemoDao testDemoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        greenDaoConfig = daoConfigMap.get(GreenDao.class).clone();
        greenDaoConfig.initIdentityScope(type);

        testDemoDaoConfig = daoConfigMap.get(TestDemoDao.class).clone();
        testDemoDaoConfig.initIdentityScope(type);

        greenDao = new GreenDao(greenDaoConfig, this);
        testDemoDao = new TestDemoDao(testDemoDaoConfig, this);

        registerDao(Green.class, greenDao);
        registerDao(TestDemo.class, testDemoDao);
    }
    
    public void clear() {
        greenDaoConfig.clearIdentityScope();
        testDemoDaoConfig.clearIdentityScope();
    }

    public GreenDao getGreenDao() {
        return greenDao;
    }

    public TestDemoDao getTestDemoDao() {
        return testDemoDao;
    }

}
