package xcvf.top.readercore.bean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "TEST_DEMO".
*/
public class TestDemoDao extends AbstractDao<TestDemo, Void> {

    public static final String TABLENAME = "TEST_DEMO";

    /**
     * Properties of entity TestDemo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Name = new Property(0, String.class, "name", false, "NAME");
        public final static Property Key = new Property(1, int.class, "key", false, "KEY");
    }


    public TestDemoDao(DaoConfig config) {
        super(config);
    }
    
    public TestDemoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"TEST_DEMO\" (" + //
                "\"NAME\" TEXT," + // 0: name
                "\"KEY\" INTEGER NOT NULL );"); // 1: key
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"TEST_DEMO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, TestDemo entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
        stmt.bindLong(2, entity.getKey());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, TestDemo entity) {
        stmt.clearBindings();
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(1, name);
        }
        stmt.bindLong(2, entity.getKey());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public TestDemo readEntity(Cursor cursor, int offset) {
        TestDemo entity = new TestDemo( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // name
            cursor.getInt(offset + 1) // key
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, TestDemo entity, int offset) {
        entity.setName(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setKey(cursor.getInt(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(TestDemo entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(TestDemo entity) {
        return null;
    }

    @Override
    public boolean hasKey(TestDemo entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
